from adumbration.materials.rhythm import composite_handler_1, composite_handler_2

rhythm_material_list = [
    composite_handler_2,
    composite_handler_2,
    composite_handler_1,
    composite_handler_1,
    composite_handler_1,
    composite_handler_1,
    composite_handler_2,
    composite_handler_1,
    composite_handler_1,
    composite_handler_1,
    composite_handler_1,
    composite_handler_1,
    composite_handler_1,
    composite_handler_2,
    composite_handler_1,
    composite_handler_1,
    composite_handler_1,
    composite_handler_1,
    composite_handler_1,
    composite_handler_2,
    composite_handler_1,
    composite_handler_1,
    composite_handler_1,
    composite_handler_1,
    composite_handler_1,
]
